CREATE TABLE IF NOT EXISTS office_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  office_id INT NOT NULL,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  status TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT fk_office_users_office
  FOREIGN KEY (office_id)
  REFERENCES offices(id)
  ON DELETE CASCADE
  ON UPDATE CASCADE,

  CONSTRAINT uq_office_users_email UNIQUE (email)
);